name: yt_clipper

on:
  push:
    branches:
      - release
      - release/*
      - test-ci

env:
  version: 3.7.0-beta.3.9.0-alpha.10
  clipper-name-win: yt_clipper_win_${{env.version}}
  clipper-name-mac: yt_clipper_mac_${{env.version}}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7.x]
        node-version: [12.x]
        os: [windows-latest, macos-latest]
        include:
          - os: windows-latest
            shortos: win
            clipper-name: ${{env.clipper-name-win}}
          - os: macos-latest
            shortos: mac
            clipper-name: ${{env.clipper-name-mac}}

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run bundle:prod --if-present

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install clipper python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U pyinstaller
          pip install -r ./src/clipper/requirements.txt

      # - name: Lint with flake8
      #   run: |
      #     pip install flake8
      #     # stop the build if there are Python syntax errors or undefined names
      #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      #     # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
      #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Generate executable
        run: npm run build:py

      - name: Set up artifacts dir
        shell: bash
        run: |
          mkdir -p ./artifact/py/${{matrix.clipper-name}}/{webms,bin}/
          mkdir -p ./artifact/js/${{matrix.clipper-name}}/

      - name: Copy artifacts
        shell: bash
        run: |
          cp ./bindeps/${{matrix.shortos}}/ffmpeg/* ./artifact/py/${{matrix.clipper-name}}/bin/
          cp ./src/clipper/${{matrix.shortos}}_helpers/* ./artifact/py/yt_clipper_${{matrix.shortos}}/
          cp ./dist/py/yt_clipper* ./artifact/py/${{matrix.clipper-name}}/
          cp ./dist/js/yt_clipper.js ./artifact/py/${{matrix.clipper-name}}/

      - name: Zip artifacts on windows
        if: matrix.os == 'windows-latest'
        run: |
          Compress-Archive ./artifact/py/${{matrix.clipper-name}}/ ./artifact/py/${{matrix.clipper-name}}.zip

      - name: Zip artifacts on non-windows systems
        if: matrix.os != 'windows-latest'
        run: |
          zip -r ./artifact/py/${{matrix.clipper-name}}.zip ./artifact/py/${{matrix.clipper-name}}/ 

      - name: Upload clipper script installation artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{matrix.clipper-name}}.zip
          path: ./artifact/py/${{matrix.clipper-name}}.zip

  release:
    needs: build
    runs-on: macos-latest

    steps:
    - uses: actions/download-artifact@v2
      with:
        name:  ${{env.clipper-name-win}}.zip

    - uses: actions/download-artifact@v2
      with:
        name:  ${{env.clipper-name-mac}}.zip

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: true
        prerelease: false

    - name: Upload release asset (win)
      id: upload-release-asset-win
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{env.clipper-name-win}}.zip
        asset_name: ${{env.clipper-name-win}}.zip
        asset_content_type: application/zip

    - name: Upload release asset (mac)
      id: upload-release-asset-mac 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{env.clipper-name-mac}}.zip
        asset_name: ${{env.clipper-name-mac}}.zip
        asset_content_type: application/zip
