name: yt_clipper

on:
  push:
    branches:
      - release
      - release/*
      - test-ci

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7.x]
        node-version: [12.x]
        os: [windows-latest, macos-latest]
        include:
          - os: windows-latest
            shortos: win
          - os: macos-latest
            shortos: mac

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run bundle:prod --if-present

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install clipper python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U pyinstaller
          pip install -r ./src/clipper/requirements.txt

      # - name: Lint with flake8
      #   run: |
      #     pip install flake8
      #     # stop the build if there are Python syntax errors or undefined names
      #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      #     # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
      #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Generate executable
        run: npm run build:py

      - name: Set up artifacts dir
        shell: bash
        run: mkdir -p ./artifact/py/yt_clipper_${{matrix.shortos}}/{webms,bin}/

      - name: Copy artifacts
        run: |
          cp ./bindeps/${{matrix.shortos}}/ffmpeg/* ./artifact/py/yt_clipper_${{matrix.shortos}}/bin/
          cp ./src/clipper/${{matrix.shortos}}_helpers/* ./artifact/py/yt_clipper_${{matrix.shortos}}/
          cp ./dist/py/yt_clipper* ./artifact/py/yt_clipper_${{matrix.shortos}}/

      - name: Upload clipper script installation artifact
        uses: actions/upload-artifact@v1
        with:
          name: yt_clipper_${{matrix.shortos}}
          path: ./artifact/py/yt_clipper_${{matrix.shortos}}/
